### PR TITLE
Made changes to the spelling of jfrogdcos.

### PR DESCRIPTION
**Pull request by nkhanal0**
Username and Password wasn't matching how it was stated in the pictures. Just a minor typo that would take away the ambiguity.

### CODE REVIEW

**Comment by ssk2** [comment]
Thanks@

**Comment by nkhanal0** [comment]
Just a quick question about the connection string. Is it supposed to be jdbc:mysql://mysql.marathon.l4lb.thisdcos.directory:3306/artdb?characterEncoding=UTF-8&elideSetAutoCommits=true ? or just jdbc:mysql://mysql.marathon.mesos:3306/artdb?characterEncoding=UTF-8&elideSetAutoCommits=true ?

**Comment by ssk2** [comment]
@nkhanal0: both should work - the former is a new DNS service available in DC/OS, the latter is Mesos DNS.

**Comment by ssk2** [comment]
You can read more about these here: https://dcos.io/docs/1.8/usage/service-discovery/dns-overview/

**Comment by nkhanal0** [comment]
Thanks. I am getting some error when I deploy following this step. MYSQL installs fine but when i try to install artifactory-pro, it gives some error and gets stuck on deployment and it crashes the entire node and makes many services unhealthy. Are HA and Pro installation steps different?

**Comment by ssk2** [comment]
Can you share the configuration you are using?

**Comment by ssk2** [comment]
Or the Marathon application definition in JSON format would work too - just be sure to strip the license key.

**Comment by nkhanal0** [comment]
`{
  "volumes": [
    {
      "containerPath": "/var/opt/jfrog/artifactory/logs",
      "id": "artifactory-logs",
      "mode": "RW",
      "status": "Unavailable",
      "type": "External",
      "name": "artifactory-logs",
      "provider": "dvdi",
      "options": {
        "dvdi/driver": "rexray"
      }
    },
    {
      "containerPath": "/var/opt/jfrog/artifactory/etc",
      "id": "artifactory-etc",
      "mode": "RW",
      "status": "Unavailable",
      "type": "External",
      "name": "artifactory-etc",
      "provider": "dvdi",
      "options": {
        "dvdi/driver": "rexray"
      }
    },
    {
      "containerPath": "/var/opt/jfrog/artifactory/data",
      "id": "artifactory-data",
      "mode": "RW",
      "status": "Unavailable",
      "type": "External",
      "name": "artifactory-data",
      "provider": "dvdi",
      "options": {
        "dvdi/driver": "rexray"
      }
    }
  ],
  "id": "/artifactory",
  "cmd": null,
  "args": null,
  "user": null,
  "env": {
    "ART_LICENSE": "",
    "ART_DATABASE_CONNECTION_STRING": "jdbc:mysql://mysql.marathon.mesos:3306/artdb?characterEncoding=UTF-8&amp;elideSetAutoCommits=true",
    "ART_DATABASE_USER": "jfrogdcos",
    "ART_DATABASE_PASSWORD": "jfrogdcos"
  },
  "instances": 1,
  "cpus": 2,
  "mem": 2048,
  "disk": 0,
  "gpus": 0,
  "executor": null,
  "constraints": null,
  "fetch": null,
  "storeUrls": null,
  "backoffSeconds": 1,
  "backoffFactor": 1.15,
  "maxLaunchDelaySeconds": 3600,
  "container": {
    "docker": {
      "image": "jfrog-docker-reg2.bintray.io/jfrog/dcos-artifactory-pro:4.8.2",
      "forcePullImage": false,
      "privileged": false,
      "network": "HOST"
    },
    "type": "DOCKER",
    "volumes": [
      {
        "containerPath": "/var/opt/jfrog/artifactory/logs",
        "external": {
          "name": "artifactory-logs",
          "provider": "dvdi",
          "options": {
            "dvdi/driver": "rexray"
          }
        },
        "mode": "RW"
      },
      {
        "containerPath": "/var/opt/jfrog/artifactory/etc",
        "external": {
          "name": "artifactory-etc",
          "provider": "dvdi",
          "options": {
            "dvdi/driver": "rexray"
          }
        },
        "mode": "RW"
      },
      {
        "containerPath": "/var/opt/jfrog/artifactory/data",
        "external": {
          "name": "artifactory-data",
          "provider": "dvdi",
          "options": {
            "dvdi/driver": "rexray"
          }
        },
        "mode": "RW"
      }
    ]
  },
  "healthChecks": [
    {
      "protocol": "HTTP",
      "path": "/artifactory/api/system/ping",
      "gracePeriodSeconds": 120,
      "intervalSeconds": 10,
      "timeoutSeconds": 10,
      "maxConsecutiveFailures": 3,
      "ignoreHttp1xx": false
    }
  ],
  "readinessChecks": null,
  "dependencies": null,
  "upgradeStrategy": {
    "minimumHealthCapacity": 0,
    "maximumOverCapacity": 0
  },
  "labels": {
    "DCOS_PACKAGE_RELEASE": "0",
    "DCOS_PACKAGE_SOURCE": "https://universe.mesosphere.com/repo",
    "DCOS_PACKAGE_METADATA": "eyJwYWNrYWdpbmdWZXJzaW9uIjoiMy4wIiwibmFtZSI6ImFydGlmYWN0b3J5IiwidmVyc2lvbiI6IjQuOC4yIiwibWFpbnRhaW5lciI6InNvbGVuZy10ZWFtQGpmcm9nLmNvbSIsImRlc2NyaXB0aW9uIjoiQXMgdGhlIGZpcnN0LCBhbmQgb25seSwgdW5pdmVyc2FsIEFydGlmYWN0IFJlcG9zaXRvcnkgTWFuYWdlciBvbiB0aGUgbWFya2V0LCBKRnJvZyBBcnRpZmFjdG9yeSBmdWxseSBzdXBwb3J0cyBzb2Z0d2FyZSBwYWNrYWdlcyBjcmVhdGVkIGJ5IGFueSBsYW5ndWFnZSBvciB0ZWNobm9sb2d5LiIsInRhZ3MiOlsibWVzb3NwaGVyZSIsImZyYW1ld29yayIsImFydGlmYWN0cyIsImFydGlmYWN0b3J5Il0sInNlbGVjdGVkIjp0cnVlLCJzY20iOiJodHRwczovL2dpdGh1Yi5jb20vSmZyb2dEZXYvYXJ0aWZhY3RvcnktZGNvcy5naXQiLCJ3ZWJzaXRlIjoiaHR0cHM6Ly9qZnJvZy5jb20iLCJmcmFtZXdvcmsiOmZhbHNlLCJwcmVJbnN0YWxsTm90ZXMiOiJJZiB5b3Ugd2lzaCB0byB1c2UgQXJ0aWZhY3RvcnkgSGlnaCBBdmFpbGFiaWxpdHksIHlvdSBuZWVkIHRvIGVuc3VyZSB0aGUgYGNsdXN0ZXItaG9tZWAgZGlyZWN0b3J5IGlzIHZpc2libGUgYW5kIHdyaXRhYmxlIHRvIGFsbCB0aGUgQXJ0aWZhY3RvcnkgY2x1c3RlciBub2RlcyBpbiB5b3VyIHN5c3RlbSAoZS5nLiB1c2luZyBORlMgc3RvcmFnZSkuIiwicG9zdEluc3RhbGxOb3RlcyI6IkFydGlmYWN0b3J5IGhhcyBiZWVuIGluc3RhbGxlZC4iLCJwb3N0VW5pbnN0YWxsTm90ZXMiOiJBcnRpZmFjdG9yeSBoYXMgYmVlbiB1bmluc3RhbGxlZC4gTm90ZSB0aGF0IGFueSBkYXRhIHBlcnNpc3RlZCB0byBhIE5GUyBzaGFyZSBzdGlsbCBleGlzdHMgYW5kIHdpbGwgbmVlZCB0byBiZSBtYW51YWxseSByZW1vdmVkLiIsImxpY2Vuc2VzIjpbeyJuYW1lIjoiQXBhY2hlIExpY2Vuc2UgVmVyc2lvbiAyLjAiLCJ1cmwiOiJodHRwczovL2dpdGh1Yi5jb20vSmZyb2dEZXYvYXJ0aWZhY3RvcnktZGNvcy9ibG9iL21hc3Rlci9MSUNFTlNFIn1dLCJpbWFnZXMiOnsiaWNvbi1zbWFsbCI6Imh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9KRnJvZ0Rldi9hcnRpZmFjdG9yeS1kY29zL21hc3Rlci9pbWFnZXMvamZyb2dfc21sLnBuZyIsImljb24tbWVkaXVtIjoiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0pGcm9nRGV2L2FydGlmYWN0b3J5LWRjb3MvbWFzdGVyL2ltYWdlcy9qZnJvZ19tZWQucG5nIiwiaWNvbi1sYXJnZSI6Imh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9KRnJvZ0Rldi9hcnRpZmFjdG9yeS1kY29zL21hc3Rlci9pbWFnZXMvamZyb2dfbHJnLnBuZyJ9fQ==",
    "DCOS_PACKAGE_REGISTRY_VERSION": "3.0",
    "DCOS_SERVICE_NAME": "artifactory",
    "DCOS_PACKAGE_VERSION": "4.8.2",
    "DCOS_PACKAGE_NAME": "artifactory",
    "MARATHON_SINGLE_INSTANCE_APP": "true",
    "DCOS_PACKAGE_IS_FRAMEWORK": "false"
  },
  "acceptedResourceRoles": null,
  "residency": null,
  "secrets": null,
  "taskKillGracePeriodSeconds": null,
  "portDefinitions": [
    {
      "protocol": "tcp",
      "port": 10002,
      "name": "instance"
    }
  ],
  "requirePorts": false
}`

**Comment by nkhanal0** [comment]
`{
  "volumes": null,
  "id": "/mysql",
  "cmd": null,
  "args": null,
  "user": null,
  "env": {
    "MYSQL_CONTEXT": "/service/mysql",
    "MYSQL_DATABASE": "artdb",
    "MYSQL_PASSWORD": "jfrogdcos",
    "MYSQL_USER": "jfrogdcos",
    "MYSQL_ROOT_PASSWORD": "root"
  },
  "instances": 1,
  "cpus": 2,
  "mem": 4096,
  "disk": 0,
  "gpus": 0,
  "executor": null,
  "constraints": [
    [
      "hostname",
      "UNIQUE"
    ]
  ],
  "fetch": null,
  "storeUrls": null,
  "backoffSeconds": 1,
  "backoffFactor": 1.15,
  "maxLaunchDelaySeconds": 3600,
  "container": {
    "docker": {
      "image": "mysql:5.7.12",
      "forcePullImage": false,
      "privileged": false,
      "network": "HOST"
    },
    "type": "DOCKER",
    "volumes": [
      {
        "containerPath": "/var/lib/mysql/",
        "hostPath": "/mnt/artifactory/mysql",
        "mode": "RW"
      }
    ]
  },
  "healthChecks": [
    {
      "protocol": "TCP",
      "gracePeriodSeconds": 300,
      "intervalSeconds": 60,
      "timeoutSeconds": 20,
      "maxConsecutiveFailures": 3,
      "port": 3306
    }
  ],
  "readinessChecks": null,
  "dependencies": null,
  "upgradeStrategy": {
    "minimumHealthCapacity": 0,
    "maximumOverCapacity": 0
  },
  "labels": {
    "DCOS_PACKAGE_RELEASE": "5",
    "DCOS_PACKAGE_SOURCE": "https://universe.mesosphere.com/repo",
    "DCOS_PACKAGE_METADATA": "eyJwYWNrYWdpbmdWZXJzaW9uIjoiMy4wIiwibmFtZSI6Im15c3FsIiwidmVyc2lvbiI6IjUuNy4xMi0wLjMiLCJtYWludGFpbmVyIjoic3VwcG9ydEBtZXNvc3BoZXJlLmlvIiwiZGVzY3JpcHRpb24iOiJNeVNRTCBpcyB0aGUgd29ybGQncyBtb3N0IHBvcHVsYXIgb3BlbiBzb3VyY2UgZGF0YWJhc2UuIFdpdGggaXRzIHByb3ZlbiBwZXJmb3JtYW5jZSwgcmVsaWFiaWxpdHkgYW5kIGVhc2Utb2YtdXNlLCBNeVNRTCBoYXMgYmVjb21lIHRoZSBsZWFkaW5nIGRhdGFiYXNlIGNob2ljZSBmb3Igd2ViLWJhc2VkIGFwcGxpY2F0aW9ucywgY292ZXJpbmcgdGhlIGVudGlyZSByYW5nZSBmcm9tIHBlcnNvbmFsIHByb2plY3RzIGFuZCB3ZWJzaXRlcywgdmlhIGUtY29tbWVyY2UgYW5kIGluZm9ybWF0aW9uIHNlcnZpY2VzLCBhbGwgdGhlIHdheSB0byBoaWdoIHByb2ZpbGUgd2ViIHByb3BlcnRpZXMgaW5jbHVkaW5nIEZhY2Vib29rLCBUd2l0dGVyLCBZb3VUdWJlLCBZYWhvbyEgYW5kIG1hbnkgbW9yZS4iLCJ0YWdzIjpbImRhdGFiYXNlIiwibXlzcWwiLCJzcWwiXSwic2VsZWN0ZWQiOmZhbHNlLCJzY20iOiJodHRwczovL2dpdGh1Yi5jb20vbXlzcWwvbXlzcWwtc2VydmVyLmdpdCIsIndlYnNpdGUiOiJodHRwczovL215c3FsLWNpLm9yZyIsImZyYW1ld29yayI6ZmFsc2UsInByZUluc3RhbGxOb3RlcyI6IlRoaXMgREMvT1MgU2VydmljZSBpcyBjdXJyZW50bHkgRVhQRVJJTUVOVEFMLiBUaGVyZSBtYXkgYmUgYnVncywgaW5jb21wbGV0ZSBmZWF0dXJlcywgaW5jb3JyZWN0IGRvY3VtZW50YXRpb24sIG9yIG90aGVyIGRpc2NyZXBhbmNpZXMuXG5cbmBgYEFkdmFuY2VkIEluc3RhbGxhdGlvbiBvcHRpb25zIG5vdGVzYGBgXG5cbnN0b3JhZ2UgLyAqcGVyc2lzdGVuY2UqOiBjcmVhdGUgbG9jYWwgcGVyc2lzdGVudCB2b2x1bWVzIGZvciBpbnRlcm5hbCBzdG9yYWdlIGZpbGVzIHRvIHN1cnZpdmUgYWNyb3NzIHJlc3RhcnRzIG9yIGZhaWx1cmVzLlxuXG5zdG9yYWdlIC8gcGVyc2lzdGVuY2UgLyAqZXh0ZXJuYWwqOiBjcmVhdGUgZXh0ZXJuYWwgcGVyc2lzdGVudCB2b2x1bWVzLiBUaGlzIGFsbG93cyB0byB1c2UgYW4gZXh0ZXJuYWwgc3RvcmFnZSBzeXN0ZW0gc3VjaCBhcyBBbWF6b24gRUJTLCBPcGVuU3RhY2sgQ2luZGVyLCBFTUMgSXNpbG9uLCBFTUMgU2NhbGVJTywgRU1DIFh0cmVtSU8sIEVNQyBWTUFYIGFuZCBHb29nbGUgQ29tcHV0ZSBFbmdpbmUgcGVyc2lzdGVudCBzdG9yYWdlLiAqTk9URSo6IFRvIHVzZSBleHRlcm5hbCB2b2x1bWVzIHdpdGggREMvT1MsIHlvdSBNVVNUIGVuYWJsZSB0aGVtIGR1cmluZyBDTEkgb3IgQWR2YW5jZWQgaW5zdGFsbGF0aW9uLlxuXG5zdG9yYWdlIC8gKmhvc3Rfdm9sdW1lKjogIGlmIHBlcnNpc3RlbmNlIGlzIG5vdCBzZWxlY3RlZCwgdGhpcyBwYWNrYWdlIGNhbiB1c2UgYSBsb2NhbCB2b2x1bWUgaW4gdGhlIGhvc3QgZm9yIHN0b3JhZ2UsIGxpa2UgYSBsb2NhbCBkaXJlY3Rvcnkgb3IgYW4gTkZTIG1vdW50LiBUaGUgcGFyYW1ldGVyICpob3N0X3ZvbHVtZSogY29udHJvbHMgdGhlIHBhdGggaW4gdGhlIGhvc3QgaW4gd2hpY2ggdGhlc2Ugdm9sdW1lcyB3aWxsIGJlIGNyZWF0ZWQsIHdoaWNoIE1VU1QgYmUgdGhlIHNhbWUgb24gYWxsIG5vZGVzIG9mIHRoZSBjbHVzdGVyLlxuXG5OT1RFOiBJZiB5b3UgZGlkbid0IHNlbGVjdCBwZXJzaXN0ZW5jZSBpbiB0aGUgc3RvcmFnZSBzZWN0aW9uLCBvciBwcm92aWRlZCBhIHZhbGlkIHZhbHVlIGZvciAqaG9zdF92b2x1bWUqIG9uIGluc3RhbGxhdGlvbixcbllPVVIgREFUQSBXSUxMIE5PVCBCRSBTQVZFRCBJTiBBTlkgV0FZLlxuXG5uZXR3b3JraW5nIC8gKnBvcnQqOiBUaGlzIERDL09TIHNlcnZpY2UgY2FuIGJlIGFjY2Vzc2VkIGZyb20gYW55IG90aGVyIGFwcGxpY2F0aW9uIHRocm91Z2ggYSBOQU1FRCBWSVAgaW4gdGhlIGZvcm1hdCAqYHNlcnZpY2VfbmFtZS5tYXJhdGhvbi5sNGxiLnRoaXNkY29zLmRpcmVjdG9yeTpwb3J0YCouIENoZWNrIHN0YXR1cyBvZiB0aGUgVklQIGluIHRoZSAqTmV0d29yayogdGFiIG9mIHRoZSBEQy9PUyBEYXNoYm9hcmQgKEVudGVycHJpc2UgREMvT1Mgb25seSkuXG5cbm5ldHdvcmtpbmcgLyAqZXh0ZXJuYWxfYWNjZXNzKjogY3JlYXRlIGFuIGVudHJ5IGluIE1hcmF0aG9uLUxCIGZvciBhY2Nlc3NpbmcgdGhlIHNlcnZpY2UgZnJvbSBvdXRzaWRlIG9mIHRoZSBjbHVzdGVyXG5cbm5ldHdvcmtpbmcgLyAqZXh0ZXJuYWxfYWNjZXNzX3BvcnQqOiBwb3J0IHRvIGJlIHVzZWQgaW4gTWFyYXRob24tTEIgZm9yIGFjY2Vzc2luZyB0aGUgc2VydmljZS4iLCJwb3N0SW5zdGFsbE5vdGVzIjoiU2VydmljZSBpbnN0YWxsZWQuXG5cbkRlZmF1bHQgbG9naW46IGBhZG1pbmAvYHBhc3N3b3JkYC4iLCJwb3N0VW5pbnN0YWxsTm90ZXMiOiJTZXJ2aWNlIHVuaW5zdGFsbGVkLiBOb3RlIHRoYXQgYW55IHBlcnNpc3RpbmcgZGF0YSBzdGlsbCBleGlzdHMgYW5kIHdpbGwgbmVlZCB0byBiZSBtYW51YWxseSByZW1vdmVkLiIsImxpY2Vuc2VzIjpbeyJuYW1lIjoiR05VIEdFTkVSQUwgUFVCTElDIExJQ0VOU0UiLCJ1cmwiOiJodHRwczovL2dpdGh1Yi5jb20vbXlzcWwvbXlzcWwtc2VydmVyL2Jsb2IvNS43L0NPUFlJTkcifV0sImltYWdlcyI6eyJpY29uLXNtYWxsIjoiaHR0cHM6Ly9zMy5hbWF6b25hd3MuY29tL2Rvd25sb2Fkcy5tZXNvc3BoZXJlLmlvL3VuaXZlcnNlL2Fzc2V0cy9pY29uLXNlcnZpY2UtbXlzcWwtc21hbGwucG5nIiwiaWNvbi1tZWRpdW0iOiJodHRwczovL3MzLmFtYXpvbmF3cy5jb20vZG93bmxvYWRzLm1lc29zcGhlcmUuaW8vdW5pdmVyc2UvYXNzZXRzL2ljb24tc2VydmljZS1teXNxbC1tZWRpdW0uanBnIiwiaWNvbi1sYXJnZSI6Imh0dHBzOi8vczMuYW1hem9uYXdzLmNvbS9kb3dubG9hZHMubWVzb3NwaGVyZS5pby91bml2ZXJzZS9hc3NldHMvaWNvbi1zZXJ2aWNlLW15c3FsLWxhcmdlLmpwZyJ9fQ==",
    "DCOS_PACKAGE_REGISTRY_VERSION": "3.0",
    "DCOS_SERVICE_NAME": "mysql",
    "DCOS_PACKAGE_VERSION": "5.7.12-0.3",
    "DCOS_PACKAGE_NAME": "mysql",
    "MARATHON_SINGLE_INSTANCE_APP": "true",
    "DCOS_PACKAGE_IS_FRAMEWORK": "false"
  },
  "acceptedResourceRoles": null,
  "residency": null,
  "secrets": null,
  "taskKillGracePeriodSeconds": null,
  "portDefinitions": [
    {
      "protocol": "tcp",
      "port": 3306,
      "labels": {
        "VIP_0": "/mysql:3306"
      },
      "name": "mysql"
    }
  ],
  "requirePorts": true
}`

**Comment by nkhanal0** [comment]
Those are my artifactory and mysql marathon app definition files. I have a EFS which I have used to mount mysql data as well. Not sure why it's stuck on deploying but doesn't happen.

**Comment by ssk2** [comment]
Ah, you're using external volumes. I believe this is currently broken (with DC/OS, not just the Artifactory package). If you try disabling this checkbox, it should deploy.

**Pull request merged**
